name: Type check and test every tag (i.e. new version)

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        poetry-version: ["1.3.2"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      # with:
      #   submodules: recursive # TODO: find out if/when I want this
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - run: poetry install --with test
      - run: poetry run mypy .
      - run: poetry run pytest
      # Lints are not checked in this workflow (it doesn't affect how well the package works)
